services:
  postgres:
    image: postgres:16
    container_name: sa_postgres
    environment:
      POSTGRES_USER: sa_user
      POSTGRES_PASSWORD: sa_password
      POSTGRES_DB: sa_db
    ports:
      - "5432:5432"
    volumes:
      - sa_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sa_redis
    ports:
      - "6379:6379"

volumes:
  sa_pgdata:
